<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<ENCPropertyForNonSOLAS:DataSet xmlns:S100="http://www.iho.int/s100gml/1.0" xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" gml:id="ENCPropertyForNonSOLAS" xmlns:ENCPropertyForNonSOLAS="http://www.iho.int/ENCPropertyForNonSOLAS/gml/1.0">
  <imember>
    <ENCPropertyForNonSOLAS:ServiceIdentification gml:id="IM.0001">
      <sourceMRN>urn:mrn:smart-navi:s:kjesv40</sourceMRN>
      <destinationMRN>urn:mrn:smart-navi:service:sv40</destinationMRN>
      <timeOfIssue>2018-12-20T16:07:20</timeOfIssue>
    </ENCPropertyForNonSOLAS:ServiceIdentification>
  </imember>
  <member>
    <ENCPropertyForNonSOLAS:Response gml:id="M.0001">
      <identification gml:id="a.0001" xlink:href="#IM.0001" xlink:role="serviceIdentification"/>
      <shipMRN>urn:mrn:smart-navi:s:kjesv40</shipMRN>
      <categoryOfService>Zone Information</categoryOfService>
      <result>ok</result>
      <information>
        <text/>
      </information>
      <zoneInformation>
        <zoneName>W1</zoneName>
        <zoneVersion>zone-181112</zoneVersion>
        <boundary>
          <northLatitude>40.0</northLatitude>
          <southLatitude>37.0</southLatitude>
          <eastLongitude>127.0</eastLongitude>
          <westLongitude>122.0</westLongitude>
        </boundary>
      </zoneInformation>
      <zoneInformation>
        <zoneName>W2</zoneName>
        <zoneVersion>zone-181112</zoneVersion>
        <boundary>
          <northLatitude>37.0</northLatitude>
          <southLatitude>36.0</southLatitude>
          <eastLongitude>127.0</eastLongitude>
          <westLongitude>122.0</westLongitude>
        </boundary>
      </zoneInformation>
      <zoneInformation>
        <zoneName>W3</zoneName>
        <zoneVersion>zone-181112</zoneVersion>
        <boundary>
          <northLatitude>36.0</northLatitude>
          <southLatitude>35.0</southLatitude>
          <eastLongitude>127.0</eastLongitude>
          <westLongitude>122.0</westLongitude>
        </boundary>
      </zoneInformation>
      <zoneInformation>
        <zoneName>S1</zoneName>
        <zoneVersion>zone-181112</zoneVersion>
        <boundary>
          <northLatitude>35.0</northLatitude>
          <southLatitude>34.0</southLatitude>
          <eastLongitude>126.0</eastLongitude>
          <westLongitude>122.0</westLongitude>
        </boundary>
      </zoneInformation>
      <zoneInformation>
        <zoneName>S2</zoneName>
        <zoneVersion>zone-181112</zoneVersion>
        <boundary>
          <northLatitude>35.0</northLatitude>
          <southLatitude>34.0</southLatitude>
          <eastLongitude>127.0</eastLongitude>
          <westLongitude>126.0</westLongitude>
        </boundary>
      </zoneInformation>
      <zoneInformation>
        <zoneName>S3</zoneName>
        <zoneVersion>zone-181112</zoneVersion>
        <boundary>
          <northLatitude>35.0</northLatitude>
          <southLatitude>34.0</southLatitude>
          <eastLongitude>128.0</eastLongitude>
          <westLongitude>127.0</westLongitude>
        </boundary>
      </zoneInformation>
      <zoneInformation>
        <zoneName>S4</zoneName>
        <zoneVersion>zone-181112</zoneVersion>
        <boundary>
          <northLatitude>35.0</northLatitude>
          <southLatitude>34.0</southLatitude>
          <eastLongitude>131.0</eastLongitude>
          <westLongitude>128.0</westLongitude>
        </boundary>
      </zoneInformation>
      <zoneInformation>
        <zoneName>S5</zoneName>
        <zoneVersion>zone-181112</zoneVersion>
        <boundary>
          <northLatitude>34.0</northLatitude>
          <southLatitude>30.0</southLatitude>
          <eastLongitude>128.0</eastLongitude>
          <westLongitude>124.0</westLongitude>
        </boundary>
      </zoneInformation>
      <zoneInformation>
        <zoneName>E1</zoneName>
        <zoneVersion>zone-181112</zoneVersion>
        <boundary>
          <northLatitude>40.0</northLatitude>
          <southLatitude>37.0</southLatitude>
          <eastLongitude>132.0</eastLongitude>
          <westLongitude>127.0</westLongitude>
        </boundary>
      </zoneInformation>
      <zoneInformation>
        <zoneName>E2</zoneName>
        <zoneVersion>zone-181112</zoneVersion>
        <boundary>
          <northLatitude>37.0</northLatitude>
          <southLatitude>36.0</southLatitude>
          <eastLongitude>132.0</eastLongitude>
          <westLongitude>128.0</westLongitude>
        </boundary>
      </zoneInformation>
      <zoneInformation>
        <zoneName>E3</zoneName>
        <zoneVersion>zone-181112</zoneVersion>
        <boundary>
          <northLatitude>36.0</northLatitude>
          <southLatitude>35.0</southLatitude>
          <eastLongitude>132.0</eastLongitude>
          <westLongitude>128.0</westLongitude>
        </boundary>
      </zoneInformation>
      <zoneInformation>
        <zoneName>SC</zoneName>
        <zoneVersion>zone-181112</zoneVersion>
        <boundary>
          <northLatitude>38.0</northLatitude>
          <southLatitude>38.0</southLatitude>
          <eastLongitude>-180.0</eastLongitude>
          <westLongitude>127.0</westLongitude>
        </boundary>
      </zoneInformation>
    </ENCPropertyForNonSOLAS:Response>
  </member>
</ENCPropertyForNonSOLAS:DataSet>
